version: "3"
services:
  frontend:
    container_name: fingrow-frontend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - fingrow-network
networks:
  fingrow-network:
    external: true
    


    
